title: 丁熠晨的个人主页
page-top-title: 丁熠晨
top-section-bg-text: 人生是一场逐渐完整的体验。
home-subtitle: 丁熠晨&ensp;|&ensp;Yichen Ding
awards-subtitle: <i class="bi bi-award-fill"></i> 荣誉
projects-subtitle: <i class="bi bi-code-slash"></i> 项目
experience-subtitle: <i class="bi bi-briefcase-fill"></i> 经历
publications-subtitle: <i class="bi bi-file-text-fill"></i>&nbsp;论文
copyright-text: '&copy; 丁熠晨 2025-2026. 保留所有权利。'
