title: Yichen's Homepage
page-top-title: Yichen Ding (丁熠晨)
top-section-bg-text: Life is an experience that gradually becomes more complete.
home-subtitle: Yichen Ding&ensp;|&ensp;丁熠晨
awards-subtitle: <i class="bi bi-award-fill"></i> AWARDS
projects-subtitle: <i class="bi bi-code-slash"></i> PROJECTS
experience-subtitle: <i class="bi bi-briefcase-fill"></i> EXPERIENCE
publications-subtitle: <i class="bi bi-file-text-fill"></i>&nbsp;PUBLICATIONS
copyright-text: '&copy; Yichen Ding 2025-2026. All Rights Reserved.'
